### PR TITLE
Support `http2` 4.2

### PR DESCRIPTION
**Pull request by 9999years**

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
Perhaps this could jump to `http2` version 5?

**Comment by Miezhiko** [comment]
I have additional patch needed, feel free to add/use it

```diff
--- a/src/Network/HTTP2/Client/Channels.hs
+++ b/src/Network/HTTP2/Client/Channels.hs
@@ -11,12 +11,14 @@ module Network.HTTP2.Client.Channels (

 import           Control.Concurrent.Chan.Lifted (Chan, readChan, newChan, writeChan)
 import           Control.Exception.Lifted (Exception, throwIO)
-import           Network.HTTP2.Frame (StreamId, FrameHeader, FramePayload, FrameType, framePayloadToFrameType, streamId)
+import           Network.HTTP2.Frame (StreamId, FrameHeader, FramePayload, FrameType, FrameDecodeError, framePayloadToFrameType, streamId)

 import           Network.HTTP2.Client.Exceptions

 type FramesChan e = Chan (FrameHeader, Either e FramePayload)

+instance Exception FrameDecodeError
+
 whenFrame
   :: Exception e
   => (FrameHeader -> FramePayload -> Bool)
```

**Comment by ProofOfKeags** [comment]
I'm not sure what to do with this PR given that it is in draft.

**Comment by Miezhiko** [comment]
> I'm not sure what to do with this PR given that it is in draft.

with merging #91 (same authorship, same commits + my fix) this one could be closed

**Pull request merged**
