### PR TITLE
base, bytestring, http2, time bounds

### PR DESCRIPTION
**Pull request by avieth**

### CODE REVIEW

**Comment by ProofOfKeags** [comment]
What is the intended ghc build target here?

I tried with 9.2 since I think base 4.16.1 is used in 0.2 and it didn't work.

It seems to work with 9.0 though.

**Comment by avieth** [comment]
> What is the intended ghc build target here?

9.2.1. I have it buliding, but I'm using nix with a custom overlay. What's the build failure you're seeing?

**Comment by ProofOfKeags** [comment]
fwiw I used 9.2.2 to test this build but here's what I got.

> Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: http2-client-0.10.0.1 (user goal)
[__1] trying: tls-1.5.7 (dependency of http2-client)
[__2] trying: memory-0.16.0 (dependency of tls)
[__3] next goal: base (dependency of http2-client)
[__3] rejecting: base-4.16.1.0/installed-4.16.1.0 (conflict: memory =>
base<4.16)
[__3] skipping: base-4.16.0.0 (has the same characteristics that caused the
previous version to fail: excluded by constraint '<4.16' from 'memory')
[__3] rejecting: base-4.15.1.0, base-4.15.0.0, base-4.14.3.0, base-4.14.2.0,
base-4.14.1.0, base-4.14.0.0, base-4.13.0.0, base-4.12.0.0, base-4.11.1.0,
base-4.11.0.0, base-4.10.1.0, base-4.10.0.0, base-4.9.1.0, base-4.9.0.0,
base-4.8.2.0, base-4.8.1.0, base-4.8.0.0, base-4.7.0.2, base-4.7.0.1,
base-4.7.0.0, base-4.6.0.1, base-4.6.0.0, base-4.5.1.0, base-4.5.0.0,
base-4.4.1.0, base-4.4.0.0, base-4.3.1.0, base-4.3.0.0, base-4.2.0.2,
base-4.2.0.1, base-4.2.0.0, base-4.1.0.0, base-4.0.0.0, base-3.0.3.2,
base-3.0.3.1 (constraint from non-upgradeable package requires installed
instance)
[__3] fail (backjumping, conflict set: base, http2-client, memory)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: tls, base, http2-client, memory
Try running with --minimize-conflict-set to improve the error message.

**Comment by avieth** [comment]
Right, looks like nixpkgs applies the patch from [this issue](https://github.com/vincenthz/hs-memory/issues/86). Also [this PR](https://github.com/vincenthz/hs-memory/pull/87). Seems Vincent is MIA.

**Comment by avieth** [comment]
Never mind, he's done it! https://twitter.com/vincenthz/status/1502992810936762368

Should build with memory 0.17

**Comment by ProofOfKeags** [comment]
What command are you running and with what configs? I've never really used cabal directly (always used stack).

Do I need to specifically install memory@0.17?

**Comment by avieth** [comment]
> What command are you running and with what configs? I've never really used cabal directly (always used stack).
> 
> Do I need to specifically install memory@0.17?

Should be enough to `cabal update` and then `cabal v2-build`.

**Comment by ProofOfKeags** [comment]
Can confirm that this seems to work. That said, I thought the `v2-*` commands were deprecated.

**Comment by avieth** [comment]
> That said, I thought the v2-* commands were deprecated.

Oh I think you're right, and the old ones are opt-in by `v1-` prefix. I just use `v2-` by force of habit.

Well, not deprecated, but renamed to unprefixed.

**Pull request merged**
