### PR TITLE
Fix build ghc98

### PR DESCRIPTION
**Pull request by lucasdicioccio**
I've got it to work with:
- ghc-9.8
- http2-5 and http2-4 (for retro compat).

Later this week/month I'll be working on adapting the gRPC libs (putatively obsoleting this client in favor of http2 which now has a client) if the deity of spare time allows :pray: .

@ProofOfKeags do you mind having a look? if it works I'll make a release on Hackage.

### CODE REVIEW

**Comment by lucasdicioccio** [comment]
Also maybe @Miezhiko you may want to take a look.

**Comment by lucasdicioccio** [comment]
I think one course for the future is to reach recent-ghc builds with the grpc-client lib so that we get a working native-gRPC story back on a decent range of GHCs/hackage-versions. Then prepare a new version on top of `http2` directly, then consider sunsetting this client so that we do not multiply packages.

**Comment by Miezhiko** [comment]
> Also maybe @Miezhiko you may want to take a look.

LGTM

**Comment by alexfmpe** [comment]
This seems to have gotten lost somehow? 
Github seems to think the merge commit https://github.com/haskell-grpc-native/http2-client/commit/0140d8fc21e240325a19da4ce641c346df5f5079 is orphaned and in master branch I see
https://github.com/haskell-grpc-native/http2-client/blob/3f36688411d22b57a5e99e410566adef1858f80d/http2-client.cabal#L30

**Comment by lucasdicioccio** [comment]
Thanks I'll have a look. Not sure what stupid stuff I did but I've been juggling between lots of repos at outrageous times.

**Comment by lucasdicioccio** [comment]
@alexfmpe the code is still in https://github.com/haskell-grpc-native/http2-client/commits/fix-build-ghc92/ I'm not 100% sure where the diff went.

**Comment by alexfmpe** [comment]
Maybe a force push overwrote master and orphaned the merge?

**Comment by lucasdicioccio** [comment]
> Maybe a force push overwrote master and orphaned the merge?

Very likely as I was playing with quite a few repos and even multiple remotes for this repo as it originates from my personal account.

I've re-merged and it does build with 9.8.2 w/o warnings

**Comment by alexfmpe** [comment]
Great. Would a hackage release be possible?

**Pull request merged**
